webtalk_init -webtalk_dir /home/aj/Desktop/RISCV-pipelined/MP2/MP2.sim/sim_1/behav/xsim/xsim.dir/tb_main_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Aug 20 03:03:40 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "ede516e7-7d6c-4e20-b21f-fae8a17b31eb" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "33df6d03e8714a908d19f4f87a2c8e5a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "56" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 20.04.2 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD A8-7600 Radeon R7, 10 Compute Cores 4C+6G" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1900.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "32175930 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "6.51_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "119820_KB" -context "xsim\\usage"
webtalk_transmit -clientid 699009202 -regid "" -xml /home/aj/Desktop/RISCV-pipelined/MP2/MP2.sim/sim_1/behav/xsim/xsim.dir/tb_main_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/aj/Desktop/RISCV-pipelined/MP2/MP2.sim/sim_1/behav/xsim/xsim.dir/tb_main_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/aj/Desktop/RISCV-pipelined/MP2/MP2.sim/sim_1/behav/xsim/xsim.dir/tb_main_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
